<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314104025 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, xp INT NOT NULL, character_id INT DEFAULT NULL, skill_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0FE03151136BE75 ON character_skill (character_id)');
        $this->addSql('CREATE INDEX IDX_A0FE03155585C142 ON character_skill (skill_id)');
        $this->addSql('CREATE TABLE skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, main_stat VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE character_skill ADD CONSTRAINT FK_A0FE03151136BE75 FOREIGN KEY (character_id) REFERENCES edgerunner (id)');
        $this->addSql('ALTER TABLE character_skill ADD CONSTRAINT FK_A0FE03155585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_skill DROP CONSTRAINT FK_A0FE03151136BE75');
        $this->addSql('ALTER TABLE character_skill DROP CONSTRAINT FK_A0FE03155585C142');
        $this->addSql('DROP TABLE character_skill');
        $this->addSql('DROP TABLE skill');
    }
}
