<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425123752 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE log ALTER is_critical DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN log.created_at IS \'\'');
        $this->addSql('ALTER INDEX idx_e67008701136be75 RENAME TO IDX_8F3F68C51136BE75');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE log ALTER is_critical SET DEFAULT false');
        $this->addSql('COMMENT ON COLUMN log.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_8f3f68c51136be75 RENAME TO idx_e67008701136be75');
    }
}
