<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312175639 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE image_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, display_name VARCHAR(255) NOT NULL, storage_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE edgerunner ADD avatar_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE edgerunner ADD CONSTRAINT FK_9E82979786383B10 FOREIGN KEY (avatar_id) REFERENCES image_file (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9E82979786383B10 ON edgerunner (avatar_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE image_file');
        $this->addSql('ALTER TABLE edgerunner DROP CONSTRAINT FK_9E82979786383B10');
        $this->addSql('DROP INDEX UNIQ_9E82979786383B10');
        $this->addSql('ALTER TABLE edgerunner DROP avatar_id');
    }
}
