<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426075431 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, character_id INT NOT NULL, contact_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_25C766051136BE75 ON character_contact (character_id)');
        $this->addSql('CREATE INDEX IDX_25C76605E7A1254A ON character_contact (contact_id)');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, image_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E6383DA5256D ON contact (image_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_from_contact BOOLEAN NOT NULL, is_read BOOLEAN NOT NULL, character_contact_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F562D9CCC ON message (character_contact_id)');
        $this->addSql('ALTER TABLE character_contact ADD CONSTRAINT FK_25C766051136BE75 FOREIGN KEY (character_id) REFERENCES edgerunner (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_contact ADD CONSTRAINT FK_25C76605E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E6383DA5256D FOREIGN KEY (image_id) REFERENCES image_file (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F562D9CCC FOREIGN KEY (character_contact_id) REFERENCES character_contact (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_contact DROP CONSTRAINT FK_25C766051136BE75');
        $this->addSql('ALTER TABLE character_contact DROP CONSTRAINT FK_25C76605E7A1254A');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E6383DA5256D');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F562D9CCC');
        $this->addSql('DROP TABLE character_contact');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE message');
    }
}
