<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312174503 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE edgerunner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, force INT NOT NULL, dexterite INT NOT NULL, intelligence INT NOT NULL, lifepoints INT NOT NULL, cyberpoints INT NOT NULL, stresspoints INT NOT NULL, is_active BOOLEAN DEFAULT NULL, player_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9E82979799E6F5DF ON edgerunner (player_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('ALTER TABLE edgerunner ADD CONSTRAINT FK_9E82979799E6F5DF FOREIGN KEY (player_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE edgerunner DROP CONSTRAINT FK_9E82979799E6F5DF');
        $this->addSql('DROP TABLE edgerunner');
        $this->addSql('DROP TABLE "user"');
    }
}
