<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260518102449 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE down_time (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, effet TEXT NOT NULL, forced BOOLEAN NOT NULL, time_cost INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE edge_runner_down_time (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, effet_bonus TEXT DEFAULT NULL, draft BOOLEAN NOT NULL, discard BOOLEAN NOT NULL, downtime_id INT NOT NULL, edgerunner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7F968D93943157B ON edge_runner_down_time (downtime_id)');
        $this->addSql('CREATE INDEX IDX_7F968D9A3AB950A ON edge_runner_down_time (edgerunner_id)');
        $this->addSql('ALTER TABLE edge_runner_down_time ADD CONSTRAINT FK_7F968D93943157B FOREIGN KEY (downtime_id) REFERENCES down_time (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE edge_runner_down_time ADD CONSTRAINT FK_7F968D9A3AB950A FOREIGN KEY (edgerunner_id) REFERENCES edgerunner (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD downtime_active BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE edge_runner_down_time DROP CONSTRAINT FK_7F968D93943157B');
        $this->addSql('ALTER TABLE edge_runner_down_time DROP CONSTRAINT FK_7F968D9A3AB950A');
        $this->addSql('DROP TABLE down_time');
        $this->addSql('DROP TABLE edge_runner_down_time');
        $this->addSql('ALTER TABLE "user" DROP downtime_active');
    }
}
