<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315110841 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_47CC8C92126F525E ON action (item_id)');
        $this->addSql('CREATE TABLE character_action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, character_id INT DEFAULT NULL, action_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E48E4F011136BE75 ON character_action (character_id)');
        $this->addSql('CREATE INDEX IDX_E48E4F019D32F035 ON character_action (action_id)');
        $this->addSql('ALTER TABLE action ADD CONSTRAINT FK_47CC8C92126F525E FOREIGN KEY (item_id) REFERENCES item (id)');
        $this->addSql('ALTER TABLE character_action ADD CONSTRAINT FK_E48E4F011136BE75 FOREIGN KEY (character_id) REFERENCES edgerunner (id)');
        $this->addSql('ALTER TABLE character_action ADD CONSTRAINT FK_E48E4F019D32F035 FOREIGN KEY (action_id) REFERENCES action (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE action DROP CONSTRAINT FK_47CC8C92126F525E');
        $this->addSql('ALTER TABLE character_action DROP CONSTRAINT FK_E48E4F011136BE75');
        $this->addSql('ALTER TABLE character_action DROP CONSTRAINT FK_E48E4F019D32F035');
        $this->addSql('DROP TABLE action');
        $this->addSql('DROP TABLE character_action');
    }
}
