<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314220105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, character_id INT DEFAULT NULL, item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8E731861136BE75 ON character_item (character_id)');
        $this->addSql('CREATE INDEX IDX_8E73186126F525E ON character_item (item_id)');
        $this->addSql('CREATE TABLE item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, is_consume BOOLEAN NOT NULL, price INT NOT NULL, charge_price INT NOT NULL, description VARCHAR(255) NOT NULL, illustration_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F1B251E5926566C ON item (illustration_id)');
        $this->addSql('ALTER TABLE character_item ADD CONSTRAINT FK_8E731861136BE75 FOREIGN KEY (character_id) REFERENCES edgerunner (id)');
        $this->addSql('ALTER TABLE character_item ADD CONSTRAINT FK_8E73186126F525E FOREIGN KEY (item_id) REFERENCES item (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E5926566C FOREIGN KEY (illustration_id) REFERENCES image_file (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_item DROP CONSTRAINT FK_8E731861136BE75');
        $this->addSql('ALTER TABLE character_item DROP CONSTRAINT FK_8E73186126F525E');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251E5926566C');
        $this->addSql('DROP TABLE character_item');
        $this->addSql('DROP TABLE item');
    }
}
