<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425195027 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stuff (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, character_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5941F83E1136BE75 ON stuff (character_id)');
        $this->addSql('ALTER TABLE stuff ADD CONSTRAINT FK_5941F83E1136BE75 FOREIGN KEY (character_id) REFERENCES edgerunner (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_item ADD is_installed BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE character_item ADD is_equipped BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE item DROP installed');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stuff DROP CONSTRAINT FK_5941F83E1136BE75');
        $this->addSql('DROP TABLE stuff');
        $this->addSql('ALTER TABLE character_item DROP is_installed');
        $this->addSql('ALTER TABLE character_item DROP is_equipped');
        $this->addSql('ALTER TABLE item ADD installed BOOLEAN DEFAULT NULL');
    }
}
