<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425131152 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_feat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, character_id INT NOT NULL, feat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D6785531136BE75 ON character_feat (character_id)');
        $this->addSql('CREATE INDEX IDX_4D678553F43C4D5C ON character_feat (feat_id)');
        $this->addSql('CREATE TABLE feat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE feat_action (feat_id INT NOT NULL, action_id INT NOT NULL, PRIMARY KEY (feat_id, action_id))');
        $this->addSql('CREATE INDEX IDX_A4B99C41F43C4D5C ON feat_action (feat_id)');
        $this->addSql('CREATE INDEX IDX_A4B99C419D32F035 ON feat_action (action_id)');
        $this->addSql('ALTER TABLE character_feat ADD CONSTRAINT FK_4D6785531136BE75 FOREIGN KEY (character_id) REFERENCES edgerunner (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_feat ADD CONSTRAINT FK_4D678553F43C4D5C FOREIGN KEY (feat_id) REFERENCES feat (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feat_action ADD CONSTRAINT FK_A4B99C41F43C4D5C FOREIGN KEY (feat_id) REFERENCES feat (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE feat_action ADD CONSTRAINT FK_A4B99C419D32F035 FOREIGN KEY (action_id) REFERENCES action (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX uniq_9e82979786383b10');
        $this->addSql('CREATE INDEX IDX_9E82979786383B10 ON edgerunner (avatar_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_feat DROP CONSTRAINT FK_4D6785531136BE75');
        $this->addSql('ALTER TABLE character_feat DROP CONSTRAINT FK_4D678553F43C4D5C');
        $this->addSql('ALTER TABLE feat_action DROP CONSTRAINT FK_A4B99C41F43C4D5C');
        $this->addSql('ALTER TABLE feat_action DROP CONSTRAINT FK_A4B99C419D32F035');
        $this->addSql('DROP TABLE character_feat');
        $this->addSql('DROP TABLE feat');
        $this->addSql('DROP TABLE feat_action');
        $this->addSql('DROP INDEX IDX_9E82979786383B10');
        $this->addSql('CREATE UNIQUE INDEX uniq_9e82979786383b10 ON edgerunner (avatar_id)');
    }
}
